version: '3'
services:

  iris:
    build:
      context: ./iris
      dockerfile: dockerfile
    container_name: iris_database
    ports:
     - "52773:52773"
     - "51773:51773"
    entrypoint: 
      - /iris-main
      - -k
      - /external/iris.key
    volumes:
    - ./iris:/external

  webserver:
    build:
      context: ./webserver
      dockerfile: dockerfile
    depends_on:
    - "iris"
    container_name: web_server
    ports:
     - "80:80"

  driver:
    build:
      context: ./driver
      dockerfile: dockerfile
    depends_on:
    - "webserver"
    container_name: ab_driver
    entrypoint:
      - main
      - -n3 
      - http://localhost
networks:
  default:
    ipam:
      config:
        - subnet: 172.177.0.0/16
